name: Svelte tests

on:
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  frontend:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: svelte
    env:
      TZ: America/New_York
    steps:
      - uses: actions/checkout@v4

      - uses: pnpm/action-setup@v4
        with:
          version: 8.12.1

      - uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: pnpm
          cache-dependency-path: svelte/pnpm-lock.yaml

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Run svelte-check
        run: pnpm check

      - name: Run unit tests
        run: pnpm test

      - name: Run component tests
        uses: cypress-io/github-action@v6
        with:
          working-directory: svelte
          install: false
          component: true
          browser: electron
